services:
  app:
    container_name: ${APP_HOST}
    build:
      context: ../..
      dockerfile: internal/deploy/Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - backend

  db:
    container_name: ${MONGO_HOST}
    image: mongo
    restart: always
    command: mongod --quiet --logpath /dev/null
    volumes:
      - mongodb:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - backend

volumes:
  mongodb:

networks:
  backend:
    driver: bridge
