services:
  app:
    container_name: "app"
    build:
      context: ../..
      dockerfile: internal/deploy/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend

  db:
    container_name: "db"
    image: mongo
    restart: always
    command: mongod --quiet --logpath /dev/null
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

volumes:
  mongodb:

networks:
  backend:
    driver: bridge
